# Generated by Django 4.2.7 on 2023-11-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
